MM-1085: changed comments in Questionnaires profiles, changed README …
Nictiz/Nictiz-STU3-Questionnaires pull request #1
Opened 2020-05-20 15:35 UTC by niekvangalen

…so that they no longer state 'MedMij' and 'Nictiz situation'

2020-05-27 15:44 UTC, ArdonToonstra commented
Changes are okay! Can be merged in my opinion.

2020-05-28 07:19 UTC, pieter-edelman-nictiz requested changes

2020-05-28 07:19 UTC, pieter-edelman-nictiz commented on Profiles/vl-Questionnaire.xml
> +  <description value="A Questionnaire resource as used within the Questionnaires (Dutch: Vragenlijsten) information standard. &#xD;&#xA;&#xD;&#xA;*NOTE*: this profile is inspired by the http://hl7.or
Ik vind dit toch wel een beetje vaag geworden, ik denk dat het nodig is om het wel wat specifieker te maken, bv:
- "to align with other FHIR materials" => "to align with other FHIR materials in the Dutch realm"
- "The profiles are geared ..." => "These profiles are geared ..."
- "The use and interpretation [...] the SDC profile do not align" => "[...] do not align with other FHIR materials in the Dutch realm"
- "The profiles are based on" => "This profile is based on"

2020-05-28 07:19 UTC, pieter-edelman-nictiz commented on Profiles/vl-QuestionnaireResponse.xml
> +  <description value="A Questionnaire resource as used within the Questionnaires (Dutch: Vragenlijsten) information standard.&#xD;&#xA;&#xD;&#xA;*NOTE*: this profile is inspired by the http://hl7.org
Zie de opmerkingen hierboven

2020-05-28 08:58 UTC, merged